### ISSUE TITLE
PHP Compile Error on Yii 2.0.12

### ISSUE THREAD

**Issue by alexeevdv** [vova07/yii2-imperavi-widget#90]
After framework update to 2.0.12 i have compile error. 

```json
{  
   "name":"PHP Compile Error",
   "message":"Access level to vova07\\imperavi\\helpers\\FileHelper::normalizeOptions() must be protected (as in class yii\\helpers\\BaseFileHelper) or weaker",
   "code":64,
   "type":"yii\\base\\ErrorException",
   "file":"/var/www/vendor/vova07/yii2-imperavi-widget/src/helpers/FileHelper.php",
   "line":17,
   "stack-trace":[  
      "#0 /var/www/vendor/vova07/yii2-imperavi-widget/src/actions/GetAction.php(90): yii\\BaseYii::autoload()",
      "#1 /var/www/vendor/vova07/yii2-imperavi-widget/src/actions/GetAction.php(90): ::spl_autoload_call()",
      "#2 /var/www/vendor/yiisoft/yii2/base/Action.php(94): vova07\\imperavi\\actions\\GetAction->run()",
      "#3 /var/www/vendor/yiisoft/yii2/base/Action.php(94): ::call_user_func_array:{/var/www/rusdevelopers.local/www/vendor/yiisoft/yii2/base/Action.php:94}()",
      "#4 /var/www/vendor/yiisoft/yii2/base/Controller.php(156): yii\\base\\Action->runWithParams()",
      "#5 /var/www/vendor/yiisoft/yii2/base/Module.php(523): yii\\base\\Controller->runAction()",
      "#6 /var/www/vendor/yiisoft/yii2/web/Application.php(102): yii\\base\\Module->runAction()",
      "#7 /var/www/vendor/yiisoft/yii2/base/Application.php(380): yii\\web\\Application->handleRequest()",
      "#8 /var/www/backend/web/index.php(18): yii\\base\\Application->run()",
      "#9 {main}"
   ]
}
```

It is definetely related to last changes in Yii framework FileHelper::normalizeOptions()

**Comment by alexeevdv** [comment]
https://github.com/yiisoft/yii2/blob/2.0.12/framework/CHANGELOG.md
```
Enh #14098: yii\helpers\BaseFileHelper::normalizeOptions() is now protected (brandonkelly)
```

**Comment by noname007** [comment]
i met this.....
